
version: '3.8'

services:
  db:
    image: postgres:13
    container_name: leitura_medidores_db
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: leitura_medidores
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - leitura_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - leitura_network

volumes:
  db_data:

networks:
  leitura_network:
